name: ci-main
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DIGITALOCEAN_VERSION:
        - "1.71.1"
        KUBECTL_VERSION:
        - "1.22.3"
        HELM_VERSION:
        - "3.7.2"
        TERRAFORM_VERSION:
        - "1.1.2"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: package
      run: source 10-package.sh
      env:
        DIGITALOCEAN_VERSION: ${{ matrix.DIGITALOCEAN_VERSION }}
        KUBECTL_VERSION: ${{ matrix.KUBECTL_VERSION }}
        HELM_VERSION: ${{ matrix.HELM_VERSION }}
        TERRAFORM_VERSION: ${{ matrix.TERRAFORM_VERSION }}
        CONTAINER_REGISTRY_PUSH: 1
        CONTAINER_REGISTRY_PATH: registry-1.docker.io/conmob/digitalocean
        CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
